name: Node.js CI

on:
  push:
    branches:
      - vinoth

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Vinoth print
        run: echo " Vinoth"

      - name: mohan print
        run: echo " mohan"

      - name: sathish print
        run: echo " sathish"

      - name: complete print
        run: echo " completed successfully!"
